README.md, index.html, main.js, style.css
1. Implemented time bar affix.
2. Correct answers with swiper.
3. Added add/remove effects:
https://www.sarasoueidan.com/blog/creative-list-effects/
4. Swiper for challenges:
http://idangero.us/swiper/get-started/
Useful links:
https://stackoverflow.com/questions/590018/getting-all-selected-checkboxes-in-an-array
=> Quiz application

main.js, quizzes/java.json, quizzes/js.json, quizzes/php.json, quizzes/typescript.json, style.css
=> Enable line breaks and tabs

README.md, main.js, quizzes/java.json, quizzes/js.json, quizzes/php.json, quizzes/sql.json
=> Change quiz type

main.js, style.css
=> Disable vertical overflow

index.html, main.js, style.css
=> #2. OOP inplementation

quizzes/java.json, quizzes/js.json
Added new quizzes for
- java
- javascript
=> Added new quizzes

index.html, main.js, style.css
=> #5. Make input field extendable

main.js
=> #38. Randomize quiz answers

main.js
=> #24. Make quiz input answers case insensitive

index.html, main.js, style.css
=> #29 Fix timer

index.html, main.js, quizzes/js.json, style.css
=> #37. Implement showing correct answers 

main.js, style.css
=> #52. Implement custom radio and checkbox style

index.html, main.js, style.css
=> #33. Fix switching between quiz types

index.html, main.js, style.css
=> #36. Add shaking animation to empty inputs

main.js, quizzes/js.json, quizzes/sql.json, style.css
=> #4. Implement multi-input type of quiz

main.js, quizzes/js.json, style.css
=> #57. Add made-by section

index.html, main.js, style.css
=> #20. Update menu and its style

index.html, main.js, quizzes/css.json, style.css
=> #49. Implement CSS quizzes

main.js, quizzes/bash.json, quizzes/js.json, style.css
=> #55. Implement bash quizzes

main.js
=> #64. Implement auto switching to the next input once the current is filled
